package org.codelibs.vespa.opensearch.config;

/**
 * Manual implementation of ProxyHandlerConfig for jar packaging.
 * When using container-plugin packaging, this class is generated by the Vespa bundle-plugin
 * from src/main/resources/configdefinitions/proxy-handler.def
 *
 * This manual implementation provides the same interface for development and testing.
 */
public class ProxyHandlerConfig {

    private final String vespaEndpoint;
    private final String documentType;
    private final String pathPrefix;

    /**
     * Constructor for manual configuration.
     * @param vespaEndpoint The Vespa endpoint URL
     * @param documentType The default document type
     * @param pathPrefix The path prefix for the proxy handler
     */
    public ProxyHandlerConfig(String vespaEndpoint, String documentType, String pathPrefix) {
        this.vespaEndpoint = vespaEndpoint != null ? vespaEndpoint : "http://localhost:8080";
        this.documentType = documentType != null ? documentType : "doc";
        this.pathPrefix = pathPrefix != null ? pathPrefix : "/";
    }

    /**
     * Default constructor with sensible defaults for testing.
     */
    public ProxyHandlerConfig() {
        this("http://localhost:8080", "doc", "/");
    }

    /**
     * Builder for fluent configuration.
     */
    public static class Builder {
        private String vespaEndpoint = "http://localhost:8080";
        private String documentType = "doc";
        private String pathPrefix = "/";

        public Builder vespaEndpoint(String vespaEndpoint) {
            this.vespaEndpoint = vespaEndpoint;
            return this;
        }

        public Builder documentType(String documentType) {
            this.documentType = documentType;
            return this;
        }

        public Builder pathPrefix(String pathPrefix) {
            this.pathPrefix = pathPrefix;
            return this;
        }

        public ProxyHandlerConfig build() {
            return new ProxyHandlerConfig(vespaEndpoint, documentType, pathPrefix);
        }
    }

    /**
     * Get the Vespa endpoint URL.
     * @return the Vespa endpoint
     */
    public String vespaEndpoint() {
        return vespaEndpoint;
    }

    /**
     * Get the document type.
     * @return the document type
     */
    public String documentType() {
        return documentType;
    }

    /**
     * Get the path prefix.
     * @return the path prefix
     */
    public String pathPrefix() {
        return pathPrefix;
    }
}
